apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-deployment
  namespace: ams-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - name: rifaz017/ams-portal
        image: rifaz017/ams-portal:latest